### ISSUE TITLE
Diseño modulable

### ISSUE THREAD

**Issue by cybercamphackathon** [PsaCrypt/Secured-Hash#1]
Sería interesante que el algoritmo de hashing y cifrado pudieran intercambiarse de forma modular, es decir, que fuera sencillo crear un módulo nuevo para usar AES + SHA-1, por ejemplo.

**Comment by PsaCrypt** [comment]
He habilitado en el código fuente la función "nula" que me sugerían para que cualquier persona pueda incluír el cifrado que desee.  En breve subiré la actualización del código fuente.  :-)
